#!/bin/bash

case $(basename "$0") in
flac2aac)
	DIRNAME="aac"
	EXTENSION="m4a"
	FFMPEG_OPTS="-c:a aac -b:a 160k"
	;;
flac2mp3)
	DIRNAME="mp3"
	EXTENSION="mp3"
	FFMPEG_OPTS="-c:a libmp3lame -q:a 0"
	;;
flac2opus)
	DIRNAME="opus"
	EXTENSION="ogg"
	FFMPEG_OPTS="-c:a libopus -b:a 128k"
	;;
*)
	echo "$0: unrecognized name"
	exit 1
	;;
esac

# Create target directory tree.
find -type f -name \*.flac				\
	| while read i ; do dirname "$i" ; done		\
	| while read i ; do mkdir -p "${DIRNAME}/$i" ; done

# Convert.
find -type f -name \*.flac				\
	| parallel --bar --eta -- ffmpeg -loglevel fatal -y -i "{}" ${FFMPEG_OPTS} "${DIRNAME}/{.}.${EXTENSION}"
