#!/bin/bash

case $(basename "$0") in
flac2aac)
	DIRNAME="aac"
	EXTENSION="m4a"
	FFMPEG_OPTS="-c:a aac -b:a 192k -c:v png -vf scale=-1:120 -ar 44100"
	;;
flac2mp3)
	DIRNAME="mp3"
	EXTENSION="mp3"
	FFMPEG_OPTS="-c:a libmp3lame -q:a 0 -vn"
	;;
flac2mp3320)
	DIRNAME="mp3320"
	EXTENSION="mp3"
	FFMPEG_OPTS="-c:a libmp3lame -b:a 320k -vn"
	;;
flac2opus)
	DIRNAME="opus"
	EXTENSION="ogg"
	FFMPEG_OPTS="-c:a libopus -b:a 128k -vn"
	;;
flac2wav)
	DIRNAME="wav"
	EXTENSION="wav"
	FFMPEG_OPTS="-c:a pcm_s16le"
	;;
*)
	echo "$0: unrecognized name"
	exit 1
	;;
esac

# Create target directory tree.
find -type f -name \*.flac -or -name \*.aiff -or -name \*.wav	\
	| while read i ; do dirname "$i" ; done		\
	| while read i ; do mkdir -p "${DIRNAME}/$i" ; done

# Convert.
find -type f -name \*.flac -or -name \*.aiff -or -name \*.wav	\
	| parallel --bar --eta -- ffmpeg -loglevel fatal -y -i "{}" ${FFMPEG_OPTS} "${DIRNAME}/{.}.${EXTENSION}"
